### ISSUE TITLE
Remove dependency on the host machine having a C++ compiler for non-test builds

### ISSUE THREAD

**Issue by bendercob** [DieTime/c-flags#3]
The Meson configuration will fail if it can't find a C++ compiler on the host machine. Since C++ is only required when building unit tests (for gtest), the build should be able to succeed with only a C compiler when the 'tests' option in meson_options.txt is set to false.

**Comment by DieTime** [comment]
@bendercob Thanks for the suggestion. I think this is easy to do. I'll try to implement this this week.

**Comment by DieTime** [comment]
@bendercob The library has been updated in meson wrapdb. You can check!

**Comment by bendercob** [comment]
Awesome, thanks.
